name: CI

on:
  push:
    branches:
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: npm install and test
        run: |
          npm install
          npm run test
        env:
          MONGODB_URI: mongodb://localhost:9000/getir-case-study
