name: CI

on:
  push:
    branches:
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: touch .env
        run: touch .env
      - name: npm install and docs build
        run: |
          npm install
          npm run test
