name: Blazing fast GitHub Pages deploy

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: npm install and docs build
        run: |
          npm install
          npm run docs
      - name: Deploy site to gh-pages branch
        uses: alex-page/blazing-fast-gh-pages-deploy@v1.0.0
        with:
          repo-token: ${{ secrets.GH_PAT }}
          site-directory: docs
